---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor-loki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki
      module: distributor
  template:
    metadata:
      labels:
        app: loki
        module: distributor
    spec:
      containers:
      - name: distributor
        image: grafana/loki:2.1.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=distributor
        - -config.file=/etc/loki/config.yaml
        ports:
        - containerPort: 3100
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.01"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/loki
      volumes:
      - name: config-volume
        configMap:
          name: loki