apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail-serviceaccount
      containers:
      - name: promtail-container
        image: grafana/promtail:2.1.0
        args:
        - -config.file=/etc/promtail/promtail.yaml
        - -print-config-stderr
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.01"
        volumeMounts:
        - name: logs
          mountPath: /var/log/pods
        - name: logs-container
          mountPath: /var/lib/docker/containers
        - name: promtail-config
          mountPath: /etc/promtail
      volumes:
      - name: logs
        hostPath:
          path: /var/log/pods
      - name: logs-container
        hostPath:
          path: /var/lib/docker/containers
      - name: promtail-config
        configMap:
          name: promtail-config