apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.3.7
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.01"
        ports:
        - containerPort: 3000
