apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex
data:
  config.yaml: |
    # auth_enabled: false
    server:
      http_listen_port: 80

      # Configure the server to allow messages up to 100MB.
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000

    distributor:
      shard_by_all_labels: true
      pool:
        health_check_ingesters: true
      ring:
        kvstore:
          store: consul
          consul: 
              host: consul.default.svc.cluster.local:8500

    ingester_client:
      grpc_client_config:
        # Configure the client to allow messages up to 100MB.
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: gzip

    ingester:
      lifecycler:
      # We want to start immediately and flush on shutdown.
        join_after: 0
        min_ready_duration: 0s
        final_sleep: 0s
        num_tokens: 512

        ring:
          kvstore:
            store: consul
            consul: 
                host: consul.default.svc.cluster.local:8500
          replication_factor: 1
      
    store_gateway:
      sharding_enabled: true
      sharding_ring:
        kvstore:
          store: consul
          consul: 
            host: consul.default.svc.cluster.local:8500

    storage:
      engine: blocks

    blocks_storage:
      backend: gcs 

      bucket_store:
        chunks_cache:
          backend: "memcached"
          memcached:
            addresses: "10.41.0.4:11211"

        metadata_cache:
          backend: "memcached"
          memcached:
            addresses: "10.41.0.4:11211"

      gcs:
        bucket_name: cortex
        service_account: "" # if empty or omitted Cortex will use your default service account as per Google's fallback logic

    compactor:
      sharding_enabled: true
      data_dir: compactor
      sharding_ring:
        kvstore:
          store: consul
          consul: 
              host: consul.default.svc.cluster.local:8500

    frontend_worker:
      frontend_address: "query-frontend.default.svc.cluster.local:9095"
      match_max_concurrent: true

    # ruler:
    #   enable_api: true
    #   enable_sharding: false
    #   storage:
    #     type: local
    #     local:
    #       directory: /tmp/cortex/rules
