apiVersion: v1
kind: Service
metadata:
  name: cortex-prometheus
spec:
  type: NodePort
  ports:
  - nodePort: 30900
    port: 9090
    protocol: TCP
  selector:
    app: prometheus
    prometheus: cortex