---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cortex
      module: distributor
  template:
    metadata:
      labels:
        app: cortex
        module: distributor
    spec:
      containers:
      - name: distributor
        image: quay.io/cortexproject/cortex:v1.6.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=distributor
        - -config.file=/etc/cortex/config.yaml
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.01"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/cortex
      volumes:
      - name: config-volume
        configMap:
          name: cortex