---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  labels:
    app: cortex
spec:
  # clusterIP: None gives a "headless" service so DNS returns all endpoints.
  clusterIP: None
  ports:
    - port: 9095
      name: grpc
    - port: 80
      name: http
  selector:
    app: cortex
    module: query-frontend